version: '3.9'

services:
  kotlinapp:
    container_name: kotlinapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/db_example
      MYSQL_USER: doctoey
      MYSQL_PASSWORD: password
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_example
      MYSQL_USER: doctoey
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: {}
